services:

    php_bundle_validate_http_response:
        restart: on-failure
        build:
            context: .
            dockerfile: ./docker/php/Dockerfile
        extra_hosts:
            - host.docker.internal:host-gateway
        env_file:
            -   path: .env
                required: false
        container_name: php_bundle_validate_http_response
        hostname: php_bundle_validate_http_response
        volumes:
          - ./:/www
        working_dir: /www
        expose:
          - "9000"
        networks:
            - docker-core-bundle-validate_http_response

networks:
    docker-core-bundle-validate_http_response:
